# Generated by Django 4.2.1 on 2023-06-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maqola',
            old_name='muallif',
            new_name='muallif1',
        ),
    ]
